Feature Staff
phuochungus/HomeLand_Apartment_Management pull request #15
Opened 2023-10-28 01:54 UTC by Daiduong1593572468

2023-11-01 08:00 UTC, NMPhap commented
@Daiduong1593572468 
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/362aaa5f-dfe2-432c-be59-cac71eaf7580)
Làm reponsive vào và kiếm tra các vấn đề khi kích thước màn hình tăng giảm

2023-11-03 08:58 UTC, Daiduong1593572468 commented
Đã fix
@NMPhap

2023-11-04 10:26 UTC, NMPhap requested changes
**ĐƯA ROUTE THÀNH MỘT ROUTE = level với dashboard không bỏ vào dashboard**
1.
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/ba706ef2-f199-4312-98ff-3dac7270901f)
Xóa chữ Vi
Lỗi font chỗ "tạo" + bỏ gạch chân + nút tạo giảm chiều cao
Search bar không bo góc, mờ -> đậm:onHover + onFocusWithin, bỏ border:onFocus, icon lệch, paddingLeft (không dích border E Container)
Padding: thêm padding
Canh giữa 
========================
Tittle: san-serif font
bachgroundColor:  Header(backgroundColor)
onHover : Clingky sửa lại cho smooth hơn
Bỏ gạch chân bodyText
=================================
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/f515f501-416f-4fd5-8a38-fa73569ab706)
Đổi font title + body => san-serif
Xem xét bỏ title
Tăng size chữ trong button
Bấm button không có thông báo
Padding bottom
Đưa button xuống dưới
Đổi ảnh nhân viên đâu
TextInput dài hơn
===================================
![Uploading image.png…]()
Đổi font body => san serif
Các lỗi tương tự màn hình sửa thông tin

2023-11-06 13:21 UTC, NMPhap requested changes
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/98f96d2e-29b0-4cc8-ac88-d7cc9da5d480)
Thêm padding cho toàn bộ sao cho các tiêu đề cách thêm vào trong 
Chữ danh sách nhân viên phải padding sâu hơn chữ Quản lý nhân viên
Nút tạo vẫn bị lệch
Đổi màu nền thành màu header còn màu của card thành trắng (đồng bộ với apartment)
Card grid giảm độ phóng khi hover (bị tràn ra màn hình )
Hình trên header card nhỏ lại không cho chạm viền 
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/fbaf8238-12ad-4c19-a50f-536e2a501eeb)
Title sửa tương tự như ở view all
chỗ ảnh đại diện cho to ra và cho nằm giữa
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/faecf4b5-b76a-4b2e-9636-4124e8810d01)
Padding/margin bottom để nút bấm không chạm viền dưới màn hình

2023-11-13 09:10 UTC, Daiduong1593572468 commented
đã fix

2023-11-13 09:10 UTC, Daiduong1593572468 commented
@NMPhap

2023-11-14 05:54 UTC, NMPhap requested changes
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/45d117a6-9cb3-4e9b-be9a-4672804af894)
Ngày sinh thì giờ ở đâu ra? => Xử lý thông tin trả về
Đang tiếng viêt Giới tính: male?
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/ff073d2c-50d5-4b52-a8b5-9bc6fc151751)
Padding card đâu PR nào cũng nhắc mà sao ko thấy làm?
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/6e7f70d2-66db-4ec9-b098-8cdb3f19a36d)
Align cho độ cao
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/d6556722-86b0-49aa-a5f6-7315b2ae0d40)
Search bar height cao lên
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/622dbb9d-d8eb-4835-aaa4-e22c0a624262)
Center ở giữa
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/77391b56-7e92-4fbd-a168-213174b4a95d)
reponsive lại
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/6af94503-fc9b-44be-9ff5-42bc42e67add)
Gender trả về male nhưng đánh checkbox nữ
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/8b808eca-5531-4c32-a425-ad5c780e8bda)
Choose file không bấm được => Nếu không thay đổi được thì để làm gì
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/81c7084b-da22-41ac-be0b-c860260cf882)
Đang staff sao lại xóa cư dân
Xóa cư dân => back ra ngoài
API get/:id không trả về thông tin vẫn cho chạy route ??? => Xử lý flow lại\
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/8956ef3f-bd74-48ed-9dd3-6bbe6aece1b3)
Searchbar font-weight khhông bold
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/606dd041-411b-4970-b96c-34bf98610217)
Lỗi font

2023-11-14 06:02 UTC, Daiduong1593572468 commented
oke đã rõ

2023-11-17 04:26 UTC, NMPhap requested changes
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/ea5dfc70-018e-4a91-990b-7e90451c286b)
Đổi ảnh không thấy đôri
Đổi công việc cũng ko thấy đổi
Xóa xong thì phải out ra về lại trang list
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/487c9bcf-a04b-42e4-80ec-a4488dd25111)
Lúc đang xử lý tìm kiếm thì bỏ loading vào
Có nút xóa tìm kiếm để reset về lại từ đâu
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/e8b6d87f-6cb0-45fa-8fb6-102d03c39060)
Animation chậm lại làm cho nó mượt hơn
Đẩy lên cao thêm tí

2023-11-18 15:40 UTC, Daiduong1593572468 commented
đã fix

2023-12-05 05:29 UTC, merged