resident + building
phuochungus/HomeLand_Apartment_Management pull request #23
Opened 2023-11-01 13:33 UTC by vocongbinh

2023-11-02 08:56 UTC, NMPhap requested changes
@vocongbinh 
PR không chạy được chức năng login
api/resident GET sai 
Xóa mất code của route khác
Xử lý data conversion tại api
Vẫn còn comment code quá nhiều
===============================
Kiểm tra xem nhánh đã chạy được local chưa, nếu rồi tìm hiểu nguyên nhân hoặc báo lại vấn đề tại sao lên production không chạy được.

2023-11-02 14:37 UTC, ManhHoDinh commented
@NMPhap bên tôi login bình thường nha admin@gmail.com password

2023-11-02 15:18 UTC, NMPhap commented
> @NMPhap bên tôi login bình thường nha [admin@gmail.com](mailto:admin@gmail.com) password

@ManhHoDinh 
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/1563daa0-4350-4fc4-a5b5-f6ae694399cb)

2023-11-03 00:48 UTC, vocongbinh commented
fĩ rồi á, vì mấy cái biến trong fe t đặt giống be nên cái data conversion t nghĩ k cần

2023-11-03 06:24 UTC, NMPhap requested changes
@vocongbinh 
1.
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/c6fcae14-f048-4b9b-a87c-bf9cdc5fc50b)
Không bấm được
2.
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/8a9ed573-2289-44be-bdef-9ceb0369bc5f)
Margin top.
3.
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/9b44e767-2e84-4295-b00d-b75319e50bfd)
Viết in chữ đầu
4.
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/fb81dd12-2474-434d-a6c8-d4322b83463d)
Icon đang không vertical center
6.
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/a7546f23-681a-4af2-8ab9-039df8fdf26b)
Không cho phép đổi gới tính à?
7.
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/1bebe130-3d21-4c6d-b5b6-524c9e1327bf)
Icon bị to
8.
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/dad2eb85-440e-48d7-897a-0923359d1897)
Đổi font thành futura
9.
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/d1ad894e-aabf-4467-bf06-0fbf577bd35b)
Lúc bấm tạo tòa nhà không cần hiện cái này
10.
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/8842e358-fb48-4c66-a270-d7fd7153c84b)
Không có thông báo thành công hay không cũng không có reset
============
Các phần khác tính sau sửa nhiêu đâu r merge trc để các function được khởi động

2023-11-03 07:04 UTC, vocongbinh commented
căn cước với giới tính sao đổi được

2023-11-03 07:24 UTC, ManhHoDinh commented
email + thông tin thanh toán optional không bắt buộc

2023-11-03 08:43 UTC, vocongbinh commented
còn cái số 4 t k biết sao chớ bên t căn giữa bth t thử đổi width height các kiểu vẫn căn giữa tại để align-items : centerr 
còn lại sửa hết rồi á

2023-11-03 15:19 UTC, NMPhap approved these changes

2023-11-03 15:41 UTC, merged