Add Contract | All Contracts| Delete Contract
phuochungus/HomeLand_Apartment_Management pull request #24
Opened 2023-11-06 15:12 UTC by ManhHoDinh

2023-11-07 07:41 UTC, NMPhap requested changes
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/bc52a1b2-7654-45df-be08-03facbba13b1)
Margin Top thêm
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/d1bbee49-f76c-4edb-87cc-15917f7f1935)
Thêm infinity list (lấy code trong phần useEffect của apartment list)
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/f64b7b0f-41db-4c3e-bc8b-8797d83f90be)
Kéo dài đường cách ra tới table
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/d8daba55-251a-40c6-b721-8da849777ebe)
Chữ đạm hơn 
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/5fa8e16a-353e-425f-bbf3-384fdbc51e5e)
Đưa con chuột vào bị đổi kiểu trỏ
Strip bảng để nhìn sinh động và khi hover đổi màu (như bảng cư dân)
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/71b23e78-2238-40bf-a86e-d0c5150938db)
Nút này màu trắng
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/0e9254ee-a808-409e-8056-2ed3e4dff3d4)
Chấm đỏ đặt sao chữ luôn (xài thẻ <sup> )
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/4fe75440-9fa4-4041-87cb-b1743ad2b592)
Đổi font thành san serif
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/67736439-1646-4dbd-b41d-4d7434d78f56)
đổi tiêu đề
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/09dd66c1-49be-42d9-a625-53aae3be504a)
Border lại để cụ thể hơn cái search bar

2023-11-08 03:30 UTC, ManhHoDinh commented
Đã sửa

2023-11-08 04:38 UTC, NMPhap requested changes
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/bc6b02e8-6736-47c3-b052-419af6c594e0)
Search bar cho căn phải
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/fe1d0327-7dbd-47db-92e6-6855c79723f3)
Thêm margin top

2023-11-09 07:39 UTC, NMPhap requested changes
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/b0c222f3-0b5a-449c-a00e-3976a9246fb7)
viet hoa chữ X trong xác nhận
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/506371ad-79fa-4157-8cfe-84888ee5745f)
Layout lại và đổi title button
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/f8e44d1f-9827-4916-bea7-578fa0fd682f)
Khống chế kích thước của drop down cho thành cuộn chuột

2023-11-11 15:41 UTC, ManhHoDinh commented
Đã chỉnh

2023-11-12 14:43 UTC, NMPhap approved these changes

2023-11-13 08:18 UTC, merged