create complain, add assign task to technician, technician create invoice to notify resident, resident can reject invoice
phuochungus/HomeLand_Apartment_Management pull request #32
Opened 2023-11-26 03:27 UTC by vocongbinh

2023-12-06 16:01 UTC, vocongbinh commented
đã sửa luôn pagination

2023-12-08 15:50 UTC, NMPhap requested changes
Route resident và route technician đang lỗi

2023-12-09 08:31 UTC, vocongbinh commented
- Bên luồng cư dân vô cái complain để tạo yêu cầu
- Qua bên Manager để assign nó cho technician (chỉ có manager của tòa mà cư dân ở mới coi được cái complain đó nên chú ý tạo quản lý cho cái tòa đó)
- Qua technician để coi task vừa được giao , có thể tạo layout báo giá gửi cho bên cư dân
- Cư dân có thể coi cái báo giá khi được tạo, có thể bấm thanh toán hoặc từ chối

2023-12-10 13:29 UTC, NMPhap requested changes
![image](https://github.com/phuochungus/HomeLand_Apartment_Management/assets/116002697/8ed99fcf-31d4-48db-9187-11e26131d107)
Lỗi khi mở nhấn assign

2023-12-11 20:01 UTC, NMPhap approved these changes

2023-12-12 01:34 UTC, merged